import React from 'react';
import { motion } from 'framer-motion';
import { ArrowLeft } from 'lucide-react';

interface LegalPageProps {
  onBack: () => void;
  title: string;
  lastUpdated: string;
  children?: React.ReactNode;
}

const LegalLayout = ({ onBack, title, lastUpdated, children }: LegalPageProps) => (
  <motion.div 
    initial={{ opacity: 0, y: 20 }}
    animate={{ opacity: 1, y: 0 }}
    exit={{ opacity: 0 }}
    className="min-h-screen bg-[#F8F7F4] pt-32 pb-24 px-6 md:px-12 lg:px-24 font-sans text-[#1A1A1A]"
  >
    <div className="max-w-3xl mx-auto bg-white p-8 md:p-16 rounded-[2rem] shadow-sm ring-1 ring-black/5">
      <button 
        onClick={onBack}
        className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest mb-12 text-gray-400 hover:text-[#FF4D00] transition-colors group"
      >
        <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
        Back to Home
      </button>

      <div className="mb-16 border-b border-gray-100 pb-12">
        <h1 className="font-sans font-black text-4xl md:text-6xl tracking-tighter mb-6 text-black leading-[1.1]">{title}</h1>
        <p className="text-gray-400 font-medium uppercase tracking-widest text-xs">Last Updated: {lastUpdated}</p>
      </div>

      <div className="prose prose-lg prose-slate max-w-none 
        prose-headings:font-black prose-headings:tracking-tight prose-headings:text-black 
        prose-h2:text-2xl prose-h2:mt-16 prose-h2:mb-6 
        prose-h3:text-xl prose-h3:mt-12 prose-h3:mb-4
        prose-p:text-gray-600 prose-p:leading-8 prose-p:mb-8 prose-p:font-medium
        prose-li:text-gray-600 prose-li:leading-8 prose-li:mb-2
        prose-strong:text-black prose-strong:font-bold
        prose-a:text-[#FF4D00] prose-a:no-underline hover:prose-a:underline
      ">
        {children}
      </div>
    </div>
  </motion.div>
);

export const PrivacyPolicy = ({ onBack }: { onBack: () => void }) => (
  <LegalLayout onBack={onBack} title="Privacy Policy" lastUpdated="May 28, 2025">
    <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
    
    <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

    <h2>Interpretation and Definitions</h2>
    <h3>Interpretation</h3>
    <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

    <h3>Definitions</h3>
    <p>For the purposes of this Privacy Policy:</p>
    <ul>
        <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
        <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
        <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Sipify.</li>
        <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
        <li><strong>Country</strong> refers to: India</li>
        <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
        <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
        <li><strong>Service</strong> refers to the Website.</li>
        <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
        <li><strong>Website</strong> refers to Sipify, accessible from <a href="https://app.sipify.app" className="text-blue-600 hover:underline">app.sipify.app</a></li>
        <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
    </ul>

    <h2>Collecting and Using Your Personal Data</h2>
    <h3>Types of Data Collected</h3>
    
    <h4>Personal Data</h4>
    <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
    <ul>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Usage Data</li>
    </ul>

    <h4>Usage Data</h4>
    <p>Usage Data is collected automatically when using the Service.</p>
    <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
    <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
    <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>

    <h4>Tracking Technologies and Cookies</h4>
    <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
    <ul>
        <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
        <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
    </ul>
    
    <h3>Use of Your Personal Data</h3>
    <p>The Company may use Personal Data for the following purposes:</p>
    <ul>
        <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
        <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
        <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
        <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services.</li>
        <li><strong>To provide You with news, special offers and general information</strong> about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
        <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
    </ul>

    <h3>Retention of Your Personal Data</h3>
    <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>

    <h3>Delete Your Personal Data</h3>
    <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
    <p>Our Service may give You the ability to delete certain information about You from within the Service.</p>
    <p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</p>

    <h2>Disclosure of Your Personal Data</h2>
    <h3>Business Transactions</h3>
    <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
    
    <h3>Law enforcement</h3>
    <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>

    <h2>Children's Privacy</h2>
    <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.</p>

    <h2>Links to Other Websites</h2>
    <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>

    <h2>Changes to this Privacy Policy</h2>
    <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>

    <h2>Contact Us</h2>
    <p>If you have any questions about this Privacy Policy, You can contact us:</p>
    <ul>
        <li>By email: <a href="mailto:hello@sipify.app" className="text-blue-600 hover:underline">hello@sipify.app</a></li>
    </ul>
  </LegalLayout>
);

export const TermsConditions = ({ onBack }: { onBack: () => void }) => (
  <LegalLayout onBack={onBack} title="Terms & Conditions" lastUpdated="January 15, 2025">
    <p>These Terms of Service ("Terms") govern your access to and use of the Services provided by Sipify ("Sipify", "Company", "we", "us", "our") to you ("Client", "Customer", "you", "your").</p>

    <p>By accessing or using our Services, you agree to be bound by these Terms. If you do not agree to these Terms, you must immediately cease using our Services.</p>

    <h3>1. Definitions</h3>
    <ul className="list-none pl-0 space-y-4">
      <li><strong>1.1 "Account"</strong> means the user profile required to access the Services, created by registering at https://app.sipify.app</li>
      <li><strong>1.2 "Brand"</strong> means your trademark and associated visual identity submitted for use with the Services</li>
      <li><strong>1.3 "Credits"</strong> means virtual credits enabling you to generate and download Content</li>
      <li><strong>1.4 "Content"</strong> means all marketing materials (texts, images, emails, ads) generated through the Services</li>
      <li><strong>1.5 "Services"</strong> means Sipify's AI-powered content creation platform enabling you to generate Content</li>
      <li><strong>1.6 "Subscription"</strong> means your enrollment and agreement to pay fees for ongoing access to the Services</li>
    </ul>

    <h3>2. Access and Use</h3>
    <p><strong>2.1 Grant of Rights.</strong> We grant you a non-exclusive, non-transferable right to access and use the Services during your Subscription period solely for your internal business purposes.</p>
    <p><strong>2.2 Restrictions.</strong> You shall not:</p>
    <ul>
        <li>Copy, reproduce, or reverse engineer the Services</li>
        <li>Use the Services for illegal purposes</li>
        <li>Upload content that violates third-party rights</li>
        <li>Attempt unauthorized access to our systems</li>
    </ul>
    <p><strong>2.3 Account Security.</strong> You are responsible for maintaining the confidentiality of your Account credentials and for all activities under your Account.</p>

    <h3>3. Services</h3>
    <p><strong>3.1 Service Delivery.</strong> Services are deemed delivered upon providing access credentials, regardless of actual usage.</p>
    <p><strong>3.2 AI-Generated Content.</strong> Due to the nature of AI, Content may not be unique and similar results may be generated for other users.</p>
    <p><strong>3.3 Account Management.</strong> You may cancel your Account at any time by emailing hello@sipify.app</p>

    <h3>4. Subscription and Payment</h3>
    <p><strong>4.1 Fees.</strong> Current pricing is displayed at https://sipify.app/pricing. We may modify fees with 30 days notice.</p>
    <p><strong>4.2 Billing Cycles.</strong></p>
    <ul>
        <li>Monthly plans: Billed monthly in advance</li>
        <li>Quarterly plans: Billed every 3 months in advance</li>
        <li>Annual plans: Billed annually in advance</li>
        <li>Automatic renewal unless cancelled</li>
    </ul>
    <p><strong>4.3 Cancellation.</strong></p>
    <ul>
        <li>Cancel by emailing hello@sipify.app</li>
        <li>Cancellation takes effect at the end of your current billing period</li>
        <li>You retain access to the Services until the end of your paid period</li>
        <li>No partial refunds for unused time (except as provided in Section 4.6)</li>
    </ul>
    <p><strong>4.4 Payment Methods.</strong> We accept major credit cards (Visa, Mastercard, American Express, Discover). You must provide accurate billing information.</p>
    <p><strong>4.5 Credits.</strong> Unused Credits do not roll over between billing periods.</p>
    <p><strong>4.6 Refund Policy.</strong></p>
    <ul>
        <li>Full refund available within 14 days of subscription date</li>
        <li>Eligibility: You must not have created more than 35 content pieces</li>
        <li>Refund requests must be sent to hello@sipify.app</li>
        <li>No refunds after 14 days or after creating more than 35 ads post-onboarding</li>
    </ul>
    <p><strong>4.7 Promotional Pricing and Discounts.</strong></p>
    <p>Any discount, promotional code, or reduced pricing applied at checkout applies only to the first billing cycle unless explicitly stated otherwise at the time of purchase. After the initial discounted period, your Subscription will automatically renew at the then-current standard rate for your Subscription Plan as displayed at https://sipify.app/pricing.</p>

    <h3>5. Intellectual Property</h3>
    <p><strong>5.1 Sipify Property.</strong> All Services, including software, algorithms, and platform elements, remain our exclusive property.</p>
    <p><strong>5.2 Your Content.</strong> You retain rights to your Brand and input materials. You grant us a license to use them solely to provide the Services.</p>
    <p><strong>5.3 Generated Content.</strong> You own the Content generated for you, subject to the non-exclusivity provisions in Section 3.2.</p>

    <h3>6. Contact Information</h3>
    <p>
      <strong>Email:</strong> hello@sipify.app<br />
      <strong>Website:</strong> https://sipify.app<br />
      <strong>Company:</strong> Sipify<br />
      <strong>Address:</strong> HSR Layout, Bangalore, India
    </p>
  </LegalLayout>
);

export const RefundPolicy = ({ onBack }: { onBack: () => void }) => (
  <LegalLayout onBack={onBack} title="Refund Policy" lastUpdated="May 28, 2025">
    <p>At Sipify, we're confident you'll love how effortlessly our AI-powered platform helps you create high-performing ad creatives, emails, and social media posts. But if you're not 100% satisfied, we've got you covered with our refund guarantee.</p>

    <h2>How It Works</h2>

    <h3>Eligibility</h3>
    <p>Our refund guarantee applies to all Sipify subscriptions purchased directly from <a href="https://sipify.app" className="text-blue-600 hover:underline">sipify.app</a>. To qualify for a full refund, you must meet ALL of the following conditions:</p>
    <ul>
        <li>Request must be made within 14 days of your subscription date</li>
        <li>You must not have created more than 35 content pieces</li>
    </ul>

    <h3>Time Frame</h3>
    <p>You have 14 days from the date of purchase to request a refund. If more than 14 days have passed, or if you've created more than 35 ads after onboarding, we won't be able to process a refund.</p>

    <h3>Requesting a Refund</h3>
    <p>To initiate a refund, contact us at <a href="mailto:hello@sipify.app" className="text-blue-600 hover:underline">hello@sipify.app</a> with your order number and a brief reason for your request. Our team will review your request and respond within 1–2 business days.</p>

    <h3>Refund Processing</h3>
    <p>Once approved, we’ll process your refund, and the amount will be credited to your original payment method within 5–10 business days. Please note that processing times may vary depending on your payment provider.</p>

    <h2>Need Help?</h2>
    <p>If you have any questions, reach out to us at <a href="mailto:hello@sipify.app" className="text-blue-600 hover:underline">hello@sipify.app</a>. We're here to ensure you have the best experience possible.</p>

    <p>Thank you for choosing Sipify — we can't wait to help you create scroll-stopping content! 🎉</p>
  </LegalLayout>
);